# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
# https://github.com/flutter/flutter/wiki/Code-generation-in-Flutter
#targets:
#  $default:
#    builders:
#      git_committed:
#        enabled: true

builders:
  git_committed:
    import: "package:cvicebnice/git_committed.dart"
    builder_factories: ["gitCommittedInfoBuilder"]
    build_extensions: {".toml": [".git.dart"]}
#    auto_apply: root_package
    auto_apply: all_packages
    build_to: source
    generate_for:
      - netlify.toml