name: cvicebnice
description: Matika do kapsy
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  cvicebnice_overlays:
    path: packages/cvicebnice_overlays
  firebase_analytics: ^9.3.8
  firebase_core: ^1.24.0
  flutter:
    sdk: flutter
  flutter_linkify: ^5.0.2
  font_awesome_flutter: ^10.2.1
  google_fonts: ^3.0.1
  intl: ^0.17.0
  pyramids_funnels:
    path: packages/pyramids_funnels
  software_keyboard:
    path: packages/software_keyboard
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  generate: true
